## import numpy

In [2]:
import numpy as np

In [3]:
result = 0
for i in range(100):
    result += i
print(result)

4950


## turn int to str

In [4]:
l = tuple(range(10)) #/list
strl = [str(c) for c in l] # turn num to str
print(strl)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [5]:
l_dif = [True, "2", 3.0, 4]
list_type = [type(item) for item in l_dif]
print(list_type)

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


## Fixed-type NumPy-style arrays

In [6]:
np.array(range(2,6))

array([2, 3, 4, 5])

In [7]:
np.array([range(i, i+3) for i in [2, 4, 6]]) # inner list are treated as rows

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## creating arrays from scratch

In [8]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((2, 4), dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full((2,3), 3.1415) # create 2x3 array filled with 3.1415

array([[3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415]])

In [11]:
np.arange(start = 0, stop = 20, step =2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(start = 0, stop = 1, num = 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
# random values between 0 and 1, uniformly distributed
np.random.random((3, 3))
np.random.normal(loc = 0, scale = 1, size = (2, 4))
# Create a 2x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (2, 3))
np.eye(3) # identidy matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.zeros(10, dtype='int16') # specify data type

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## set random seed

In [15]:
np.random.seed(0)  # seed for reproducibility
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
print('array shape:', x2.shape)
x2.itemsize # item size
x2.nbytes # total size

array shape: (3, 4)


96

In [16]:
print(x2)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


## resign value

In [17]:
x2[0, 0] = 3.94
print(x2) # this will be truncated/floor

[[3 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


## slicing

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[:5]

array([0, 1, 2, 3, 4])

In [20]:
x[4:7]

array([4, 5, 6])

In [21]:
x[::2] # every other eleme

array([0, 2, 4, 6, 8])

In [22]:
x[3::2] # every other element starting at index 3 ; Pattern is from, to, step

array([3, 5, 7, 9])

In [23]:
x[::-1] # reversed !!!!

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
x2 = np.random.randint(0, 10, (3, 4))
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [25]:
x2[:2, :3]

array([[8, 8, 1],
       [7, 7, 8]])

In [26]:
x2[::-1, ::-1]


array([[9, 8, 9, 5],
       [1, 8, 7, 7],
       [6, 1, 8, 8]])

## return views rather than copies !!!

In [27]:
x2_sub = x2[:2, :2]
print(x2)
x2_sub[0, 0] = -99
print(x2_sub)
print(x2) ## also changed!!!!!

[[8 8 1 6]
 [7 7 8 1]
 [5 9 8 9]]
[[-99   8]
 [  7   7]]
[[-99   8   1   6]
 [  7   7   8   1]
 [  5   9   8   9]]


This default behavior is actually quite useful:

it means that when we work with large datasets,

we can access and process pieces of these datasets without the need to copy the underlying data buffer.

## create copies of arrays

In [28]:
x2_sub_copy = x2[:2, :2].copy()

In [29]:
x2_sub_copy

array([[-99,   8],
       [  7,   7]])

In [30]:
x2_sub_copy[0, 0] = 88888

In [32]:
print(x2_sub_copy)
print(x2) # will NOT changed !!!

[[88888     8]
 [    7     7]]
[[-99   8   1   6]
 [  7   7   8   1]
 [  5   9   8   9]]


## reshape by rows

In [34]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
x = np.array([1, 2, 3])
print(x.reshape((3, 1)))
# row vector via reshape
x.reshape((1, 3))

[[1]
 [2]
 [3]]


array([[1, 2, 3]])

## Array concatenation 

In [59]:
x = np.random.randint(3, size = (1, 3)) # two dimen
y = np.random.random( size = (1, 3))
np.concatenate([x, y])

array([[1.        , 1.        , 1.        ],
       [0.66676672, 0.67063787, 0.21038256]])

In [58]:
np.concatenate([x, y], axis = 1)

array([[0.        , 1.        , 0.        , 0.6818203 , 0.3595079 ,
        0.43703195]])

In [62]:
x = np.array(range(3))
grid = np.ones(shape = (2, 3))

In [64]:
np.vstack([x, grid]) # stack the elements in the list

array([[0., 1., 2.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
y = np.zeros(shape = (2, 1))

In [68]:
np.hstack([y, grid])

array([[0., 1., 1., 1.],
       [0., 1., 1., 1.]])

## Array splitting

In [70]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [74]:
grid = np.arange(16).reshape((4, 4))
print(grid)

upper, lower, bot = np.vsplit(grid, [2, 3])
print(upper)
print(lower)
bot

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]


array([[12, 13, 14, 15]])