In [10]:
import pandas as pd
import numpy as np
pd.__version__

'0.25.3'

## The pandas series object

In [5]:
series = pd.Series([0.25, 0.5, 0.75, 1])
series # indexed data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

## values and index two attribute

In [6]:
series.values # index 

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
series[1:3]

1    0.50
2    0.75
dtype: float64

## use index

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data


a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b'] # like dictionary

0.5

In [1]:
dictn = {'a': 'lucy', 'b': 100}

In [6]:
dictn.get('c', 0)
dictn['d'] = 'Kevin'
dictn

{'a': 'lucy', 'b': 100, 'd': 'Kevin'}

## `Series`-as-dictionary analogy 

In [18]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

## supports array-style operations such as slicing

In [20]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [22]:
population[0:3]

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [23]:
pd.Series({2:'a', 1:'b', 3:'c'}) # keys become index

2    a
1    b
3    c
dtype: object

## The pandas dataframe object

In [29]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area


California    423967
Texas         695662
New York      141297
Florida       170312
dtype: int64

In [30]:
states = pd.DataFrame({'population': population,
                       'area': area})
states # automaticlly join the two series by their index 

population      area
California    38332521  423967.0
Florida       19552860  170312.0
Illinois      12882135       NaN
New York      19651127  141297.0
Texas         26448193  695662.0

In [31]:
states.index # row names

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [32]:
states.columns # col names

Index(['population', 'area'], dtype='object')

In [33]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [34]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [35]:
# data should have the same keys as the col names
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [38]:
data_new = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])
data_new

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [41]:
data_new.columns = ['dd', 'ee', 'ff'] # can change names as in R

In [40]:
data_new

dd  ee   ff
0  1.0   2  NaN
1  NaN   3  4.0

## from a array to a DF

In [42]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])


foo       bar
a  0.480803  0.490689
b  0.415467  0.031447
c  0.756063  0.572620

## Index as ordered set

In [43]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [44]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [45]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [46]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

## use dictionary-like key

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [48]:
'a' in data

True

In [50]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [51]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [52]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [53]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [54]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [12]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [56]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

## indexers

In [57]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data


1    a
3    b
5    c
dtype: object

In [58]:
# explicit index when indexing
data[1]


'a'

In [59]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

## the `loc` attribute allows indexing and slicing that always references the explicit index

In [60]:
data.loc[1]

'a'

In [67]:
data.loc[1:3]

1    a
3    b
dtype: object

## The `iloc` attribute allows indexing and slicing that always references the implicit Python-style index

In [63]:
data.iloc[1]

'b'

In [66]:
data.iloc[1:3]

3    b
5    c
dtype: object

## dataFrame as a dictionary

In [13]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [14]:
data.area # like data$area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [15]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [18]:
np.all(data.area == data['area'])

True

In [19]:
data.area is data['area']

True

## use `data['pop'] = z` rather than `data.pop = z`

In [20]:
data.pop

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [73]:
data['density'] = data['pop'] / data['area'] # add a new column
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## transpose

In [74]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

##  passing a single index to an array accesses a row:

In [75]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

## passing a single index to a DataFrame accesses a column

In [25]:
data[['area', 'pop']]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

## `.loc` and `iloc`

In [77]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

## The ix indexer allows a hybrid of these two approaches

In [21]:
data.ix[:3, :'pop']

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
//anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [79]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

## indexing refers to columns, slicing refers to rows: !!!!

In [23]:
data['Florida':'Illinois']


area       pop
Florida   170312  19552860
Illinois  149995  12882135

In [24]:
data[1:3]


area       pop
Texas     695662  26448193
New York  141297  19651127

##  masking operations are also interpreted row-wise rather than column-wise:

In [82]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121